[package]
name = "sp1-kzg-insert"
version = "0.1.0"
edition = "2021"

[dependencies]
blake3 = { version = "1.8", default-features = false }
banderwagon = { git = "https://github.com/crate-crypto/rust-verkle", rev = "e27b8b4edf1992b4afa636c2fc7983bcc27ddb88" }
num = { version = "0.4", default-features = false }
sp1-curves = "6.2.4"
sp1-programs-common = { path = "../common" }
sp1-zkvm = { version = "6.2.2" }
verkle-trie = { git = "https://github.com/crate-crypto/rust-verkle", rev = "e27b8b4edf1992b4afa636c2fc7983bcc27ddb88" }
verkle-spec = { git = "https://github.com/crate-crypto/rust-verkle", rev = "e27b8b4edf1992b4afa636c2fc7983bcc27ddb88" }
