[workspace]
members = [
    "crates/common",
    "crates/eth-sync",
    "crates/mock-chain",
    "crates/nizk",
    "crates/smt",
    "crates/smt-bench",
    "crates/sp1-programs/common",
    "crates/sp1-programs/init-merkle",
    "crates/sp1-programs/smt-update",
    "crates/sp1-programs/smt-insert",
    "crates/sp1-programs/kzg-insert",
    "crates/sp1-host",
    "crates/poa-cli",
    "crates/poa-bench",
]
resolver = "2"

[patch.crates-io]
bulletproofs-bls = { path = "vendor/bulletproofs-bls" }
k256 = { git = "https://github.com/sp1-patches/elliptic-curves", tag = "patch-k256-13.4-sp1-6.2.0" }
