[package]
name = "kzg-prover-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bls12-381 = "0.5"
ark-ec = { version = "0.5", features = ["parallel"] }
ark-ff = { version = "0.5", features = ["parallel"] }
ark-std = { version = "0.5", features = ["parallel"] }
rand = "0.8"
rayon = "1.10"

[profile.release]
lto = "thin"
codegen-units = 1

[workspace]
