[package]
name = "poa-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bls12-381 = "0.6"
ark-ff = "0.6"
common = { path = "../common" }
eth-sync = { path = "../eth-sync" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
blake3 = "1.8"
mock-chain = { path = "../mock-chain" }
nizk-fixed-set = { path = "../nizk" }
smt = { path = "../smt" }
sp1-host = { path = "../sp1-host", features = ["smt-sp1"] }
