[package]
name = "sp1-programs-common"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
k256 = { version = "0.13.4", default-features = false, features = ["ecdsa"] }
sha3 = { version = "0.10", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
slop-algebra = "6.2.4"
sp1-lib = { version = "6.2.4", default-features = false }
sp1-primitives = "6.2.4"
